# Name of the chart.
nameOverride: kubeip
# Fully qualified app name.
fullnameOverride: kubeip

# The cloud provider where your Kubernetes cluster is running.
# This value determines the appropriate annotations for the Service Account.
# Currently acceptable values are 'gcp' or 'aws'.
cloudProvider: gcp

# The namespace where the kubeip-agent will be deployed.
namespaceOverride: kube-system

# Configuration settings for the container image.
image:
  repository: doitintl/kubeip-agent
  tag: latest
  # digest: "sha256:xxx"

# Configuration for the Kubernetes Service Account.
serviceAccount:
  create: true
  name: kubeip
  annotations:
    gcpServiceAccountEmail: GCP-SA-NAME@GCP-PROJECT-NAME.iam.gserviceaccount.com
    awsRoleArn: arn:aws:iam::111122223333:role/my-role

# Role-Based Access Control (RBAC) configuration.
rbac:
  create: true

# DaemonSet configuration.
daemonSet:
  terminationGracePeriodSeconds: 30
  priorityClassName: system-node-critical
  env:
    # PROJECT: GCP-PROJECT-NAME
    # REGION: GCP-REGION
    FILTER: labels.kubeip=reserved;labels.environment=demo
    # RETRY_INTERVAL: 60s
    # RETRY_ATTEMPTS: 60
    # RELEASE_ON_EXIT: true
    LOG_LEVEL: info
    LOG_JSON: true
  resources:
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 128Mi
  nodeSelector:
    kubeip: use
    nodegroup: public
